### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by crssi** [tartpvule/custom-cors-control#1]
Since this WE is not available on AMO, could you provide installation instruction?
Could you deploy it on AMO?

Cheers

**Comment by tartpvule** [comment]
@crssi, added instructions.
As for deploying on AMO, I don't think it is ready. It is not adequately tested and I am not comfortable with releasing it with security bugs to general users.

**Comment by crssi** [comment]
I am on FF 65.0.1, so over about:debugging... but I get error `not valid mainfest` and it does not load.

Cheers

**Comment by tartpvule** [comment]
@crssi Hmm...
I am on Firefox ESR 60.5.1, no issues with loading the manifest here. Zipping the repository up into an .xpi and "Load Temporary Add-on" works too, so does pointing it to the manifest.json in a directory.

1. Could you open Tools -> Web Developer -> Browser Console and record the error message there?
2. (If applicable) Are you zipping the files or the directory containing the files?

**Comment by tartpvule** [comment]
@crssi Just "Load Temporary Add-on" in Firefox 65.0.1 on Linux, works OK there too, with `xpinstall.signatures.required` = `true`.

**Comment by crssi** [comment]
My bad. I have downloaded your project as zip and didn't realize that there was a folder with the files in it, instead only files without folder. Rezipping without folder does the job.

Cheers and thank you... will close this issue now.
